### ISSUE TITLE
katello-deploy should fail earlier

### ISSUE THREAD

**Issue by elyezer** [Katello/forklift#158]
We use katello-deploy in jenkins and would be really good if it fail if some expected command returns a non-zero return code. Currently katello-deploy aways return 0 as return code and this make the jenkins think that it went good but it actually went bad.

**Comment by omaciel** [comment]
@ehelms ping?

**Comment by ehelms** [comment]
Would bubbling up return codes from commands executed as a system command suffice?

**Comment by elyezer** [comment]
The idea is that if a command like enabling repos fail the katello-deploy should not continue. Or making it returning a non-zero if something went wrong that should suffice. In our use case we don't run the katello-installer and will not do if a non-zero return code is returned.

**Comment by ekohl** [comment]
A lot has changed in this repo. Is this still an issue?

**Comment by elyezer** [comment]
I see some `exit(1)` on the code it seems to be exiting when something fail.

I am wondering if exit(1) should be called on lines 120 and 124 of https://github.com/Katello/forklift/blob/master/setup.rb#L128 as well.

**Comment by ehelms** [comment]
@elyezer we are moving away from setup.rb all together so I'm not sure how valid the issue is now a days

**Comment by elyezer** [comment]
With that said I think we can close it then. I am going to close and we can reopen if needed.

Thank you @ehelms
