### ISSUE TITLE
404 Errors on packages

### ISSUE THREAD

**Issue by five0va** [Katello/forklift#202]
I'm getting a 404 on the below packages, causing the install to fail. I checked the repos and 1.10.1 of foreman-release is not available neither is 2.4.0 of Katello-repos are available. 

No Presto metadata available for foreman
No Presto metadata available for katello
foreman-release-1.10.1-1.el7.n FAILED                                          
http://yum.theforeman.org/releases/1.8/el7/x86_64/foreman-release-1.10.1-1.el7.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found                                    ]  0.0 B/s |    0 B  --:--:-- ETA 
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/

katello-repos-2.4.0-5.el7.noar FAILED                                          
https://fedorapeople.org/groups/katello/releases/yum/2.2/katello/RHEL/7/x86_64/katello-repos-2.4.0-5.el7.noarch.rpm: [Errno 14] HTTPS Error 404 - Not Found         ]  0.0 B/s |    0 B  --:--:-- ETA 
Trying other mirror.

**Comment by ekohl** [comment]
The problem is that you're trying to download the foreman-release-1.10.1-1 from the 1.8 directory and 2.4.0-5.el7 from the 2.2 directory. Please have a look at the newer release directories, they should be there.

**Comment by ehelms** [comment]
@five0va is this still an issue for you? I will close in 3 days unless you say otherwise.

**Comment by ekohl** [comment]
I think those 3 days passed by now :)
