### ISSUE TITLE
[Refactor] - Convert installer shell commands to an ansible module

### ISSUE THREAD

**Issue by komidore64** [Katello/forklift#304]
### needs to support
- [x] scenarios https://github.com/Katello/forklift/pull/322
- [ ] parity with `setup.rb` options and functionality
- [x] puppet module PRs https://github.com/Katello/forklift/pull/322
- [x] koji scratch build packages ([more info](https://github.com/Katello/forklift/pull/275))
- [x] all devel installations ([more info](https://github.com/Katello/forklift/pull/279))

**Comment by ekohl** [comment]
I wonder if https://github.com/kostyrevaa/ansible-role-foreman would be a good starting point.

**Comment by ekohl** [comment]
All related PRs were merged. Do we already have parity?

**Comment by komidore64** [comment]
As far as I know, yes. @stbenjam can you speak more to this?

**Comment by ekohl** [comment]
Given setup.rb was removed I'm going to close this.
