### ISSUE TITLE
pulp puppet-content dir

### ISSUE THREAD

**Issue by troubleshooter713** [Katello/forklift#324]
Guys,

I'm working with forklift and I am trying to get katello-nightly up and running and I get to this error for the 6th time. I'm not exactly sure where to find this switch to change it, can you point me in the right direction. This is the failure message that comes up:

`foreman-proxy-plugin-pulp-puppet-content-dir invalid: "" is not an absolute path`

I get this regardless if I use vagrant or ansible.

also the libvirt boxes have less than 4 gig of ram, so foreman-installer -i fails because of lack of ram. I am sure I can edit the Vagrantfile, but just wondering if this is something that anyone else has come across.

**Comment by stbenjam** [comment]
It's not a forklift problem it's a known issue in our nightlies, that will be fixed by https://github.com/theforeman/puppet-foreman_proxy/pull/303

You could use a supported release like 3.1 or the 3.2 RC instead of nightly.

**Comment by stbenjam** [comment]
> also the libvirt boxes have less than 4 gig of ram, so foreman-installer -i fails because of lack of ram. I am sure I can edit the Vagrantfile, but just wondering if this is something that anyone else has come across.

Ah you can pass "--disable-system-checks" as an installer option, but 4gb is really not enough for Katello.

**Comment by troubleshooter713** [comment]
Thanks! I think this is the direction that I needed!
