### ISSUE TITLE
vagrant up missing nokogiri

### ISSUE THREAD

**Issue by thomasmckay** [Katello/forklift#337]
On f24, made a new rvm env:
gem install bundler
bundle install
vagrant up sat62-ga-rhel7
error: missing nokogiri
gem install nokogiri
vagrant up sat62-ga-rhel7
error: missing nokogiri

Bringing machine 'sat62' up with 'libvirt' provider...
/usr/share/gems/gems/nokogiri-1.6.8.1/lib/nokogiri.rb:32:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
	from /usr/share/gems/gems/nokogiri-1.6.8.1/lib/nokogiri.rb:32:in `rescue in <top (required)>'
	from /usr/share/gems/gems/nokogiri-1.6.8.1/lib/nokogiri.rb:28:in `<top (required)>'
	from /home/thomasmckay/.vagrant.d/gems/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:1:in `require'
	from /home/thomasmckay/.vagrant.d/gems/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:1:in `<top (required)>'
	from /home/thomasmckay/.vagrant.d/gems/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action.rb:43:in `require'
	from /home/thomasmckay/.vagrant.d/gems/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action.rb:43:in `block (2 levels) in action_up'
	from /usr/share/vagrant/lib/vagrant/action/builtin/call.rb:47:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/vagrant/lib/vagrant/machine.rb:224:in `action_raw'
	from /usr/share/vagrant/lib/vagrant/machine.rb:199:in `block in action'
	from /usr/share/vagrant/lib/vagrant/environment.rb:561:in `lock'
	from /usr/share/vagrant/lib/vagrant/machine.rb:185:in `call'
	from /usr/share/vagrant/lib/vagrant/machine.rb:185:in `action'
	from /usr/share/vagrant/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by thomasmckay** [comment]
Solution is to 'rvm use system'. Is this worth documenting? The setup instructions are very light in the README

**Comment by stbenjam** [comment]
I've never gotten vagrant to work in RVM, so I always use rvm system, it's probably worth having some basic install/usage instructions on vagrant in the README.

**Comment by ekohl** [comment]
I'm in favour of closing this now. Agreed?

**Comment by ehelms** [comment]
:+1:

**Comment by ekohl** [comment]
Closing for now.
