### ISSUE TITLE
katello-certs-check not found on -devel install

### ISSUE THREAD

**Issue by dLobatog** [Katello/forklift#341]
Since the foreman-installer-katello-devel does not contain `katello-certs-check`, but one of the hooks of the installer *uses* it, the installer run fails on forklift with `which: no katello-certs-check in (/sbin:/bin:/usr/sbin:/usr/bin)`. 

The options I can think to fix this are:
1. https://github.com/Katello/katello-installer/blob/cbdace605427885a0773ed7a1dd9383748cd9fe1/hooks/pre/20-certs_update.rb update the hook to dismiss the check for certs when in `-devel`
2. Install katello-certs-check in devel too - probably preferred. https://github.com/Katello/katello-packaging/blob/a53fad639654bcbdd2db3b853bb7768f3cbd6a8d/katello-installer/katello-installer-base.spec (it's only installed with the regular katello installer)

**Comment by dLobatog** [comment]
A way to workaround is to ssh in the instance and install `foreman-installer-katello` (which also gets you katello-service 😄 ) - is there anything wrong with having both packages? I do miss katello-service in devel

**Comment by ekohl** [comment]
https://github.com/Katello/forklift/pull/342
